### PR TITLE
Added run script to make it easy

### PR DESCRIPTION
**Pull request by riipandi**

### CODE REVIEW

**Comment by IndraGunawan** [comment]
Hi @riipandi first thanks for your PR.

could you give some explanations about changes that you made?
could you give me reason why you:
- delete `composer.lock` file?
- rebuild the whole homepage and put your name on that?
- have you tested the `run.sh` script?

**Comment by riipandi** [comment]
Ups, sorry about removed lock file, and the index page that I had modify is just for personal mirror. I forgot to move the branch.

The run script will detect, first run or do the mirroring process, then create cron file.

Yes, I have already test the run script on Debian Stretch and Ubuntu 18.04. But, the script should be can run at other Linux distro.

**Comment by IndraGunawan** [comment]
could you revert any unrelated files?

**Comment by IndraGunawan** [comment]
hi @riipandi , i close this PR because no response from you.
thank you

**Pull request closed without merging**
